name: modugo
version: 3.2.5
homepage: https://github.com/bed72/Modugo
repository: https://github.com/bed72/Modugo
description: Modular Routing and Dependency Injection for Flutter with GetIt and GoRouter.

logo: modugo_logo.png
screenshots:
  - description: 'Modugo Logo'
    path: art/modugo_logo.png
topics:
  - navigation
  - routing
  - modugo
  - injection
  - deep-linking

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  event_bus: ^2.0.1
  go_router: ^16.1.0
  talker_logger: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
