name: modugo
version: 2.4.9
homepage: https://github.com/bed72/Modugo
repository: https://github.com/bed72/Modugo
description: Modular Routing and Dependency Injection for Flutter with GoRouter.

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.2.4
  talker_logger: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
