name: modugo
version: 0.0.1
homepage: https://www.elo7.com.br/
description: "A new Flutter package project."

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  equatable: ^2.0.7
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
