name: modugo
version: 0.0.1
homepage: https://www.elo7.com.br/
description: "A new Flutter package project."

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  logger: ^2.5.0
  go_router: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
