name: modugo
version: 4.1.0
homepage: https://github.com/bed72/Modugo
repository: https://github.com/bed72/Modugo
description: Modular Routing and Dependency Injection for Flutter with GetIt and GoRouter.

screenshots:
  - description: "Modugo Logo"
    path: images/logo.png
topics:
  - modugo
  - routing
  - injection
  - navigation
  - deep-linking

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
