name: modugo
version: 2.3.4
homepage: https://github.com/bed72/Modugo
repository: https://github.com/bed72/Modugo
description: Roteamento modular e injeção de dependências para Flutter com GoRouter.

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.6.0
  go_router: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
