name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: dart format --output=none --set-exit-if-changed .

      - run: flutter analyze

      - run: flutter test --coverage

      - name: Package Analysis
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          failOnWarnings: true
